version: '3.8'
services:
  db:
    image: postgres:12.6
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - ./tmp/postgresql/data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: docker-web
    command: "rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/railsapp
    ports:
      - "3000:3000"
    depends_on:
      - db

